### ISSUE TITLE
icon need for the app

### ISSUE THREAD

**Issue by sukhbir-singh** [appteam-nith/festnimbus#14]
Currently app is having default icon of android. So a better app icon is in need for the project.
Submitted icon must be related to Nimbus fest.
![ic_launcher](https://cloud.githubusercontent.com/assets/13816752/13147163/2c3328fa-d67e-11e5-82f2-7717baee3488.png)

**Comment by jaykay12** [comment]
Since official icon for nimbus 2k16 is not yet launched so can v hav the last year icon. :smile:

**Comment by appteam-nith** [comment]
still!!! lets encourage some creativity

**Comment by appteam-nith** [comment]
closed due to #37
